name: Release Extension

on:
  push:
    tags:
      - 'v*'

jobs:
  build-and-release:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        
      - name: Setup Bun
        uses: oven-sh/setup-bun@v1
        with:
          bun-version: latest
          
      - name: Install dependencies
        run: bun install
      
      - name: Get version from tag
        id: get_version
        run: echo "VERSION=${GITHUB_REF#refs/tags/v}" >> $GITHUB_OUTPUT
        
      - name: Update manifest version
        run: |
          jq '.version = "${{ steps.get_version.outputs.VERSION }}"' manifest.json > manifest.json.tmp
          mv manifest.json.tmp manifest.json
        
      - name: Create production build
        run: |
          echo "NEYNAR_API_KEY=${{ secrets.NEYNAR_API_KEY }}" > .env
          echo "NEYNAR_API_URL=${{ secrets.NEYNAR_API_URL }}" >> .env
          echo "CACHE_DURATION=3600000" >> .env
          bun run build
          rm .env
        
      - name: Create ZIP file
        run: |
          cd dist
          zip -r ../purplehawk-v${{ steps.get_version.outputs.VERSION }}.zip *
        
      - name: Create GitHub Release
        uses: softprops/action-gh-release@v1
        with:
          files: purplehawk-v${{ steps.get_version.outputs.VERSION }}.zip
          draft: false
          prerelease: false
          generate_release_notes: true
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}